package com.example.masterai.utils;

import com.example.masterai.model.Media;
import com.example.masterai.model.Post;
import java.util.ArrayList;
import java.util.Collections;

public class MockDataGenerator {

    public static ArrayList<Post> getMockPosts() {
        ArrayList<Post> posts = new ArrayList<>();

        // Post 1: AI Cyberpunk City
        Post post1 = new Post("AI_Artist_01", "Check out this amazing cyberpunk city generated by MasterAI! #AI #Cyberpunk", "public");
        post1.setMedia(Collections.singletonList(
            new Media("https://pollinations.ai/p/cyberpunk%20city%20neon%20lights%20highly%20detailed", "image", "ai", 0)
        ));
        posts.add(post1);

        // Post 2: AI Portrait
        Post post2 = new Post("Creative_Mind", "AI is getting better at portraits. What do you think of this fantasy princess?", "public");
        post2.setMedia(Collections.singletonList(
            new Media("https://pollinations.ai/p/portrait%20of%20a%20warrior%20princess%20fantasy%20art", "image", "ai", 0)
        ));
        posts.add(post2);

        // Post 3: Social Text
        Post post3 = new Post("NewUser_99", "Just joined MasterAI! Excited to see everyone's creations.", "public");
        posts.add(post3);

        // Post 4: AI Anime
        Post post4 = new Post("AnimeFan_AI", "My new anime style art generated by AI. The colors are so vibrant!", "public");
        post4.setMedia(Collections.singletonList(
            new Media("https://pollinations.ai/p/anime%20girl%20in%20a%20forest%20studio%20ghibli%20style", "image", "ai", 0)
        ));
        posts.add(post4);

        // Post 5: AI Architecture
        Post post5 = new Post("Arch_Future", "Architecture of the future. Sustainable and green. #AIArchitecture", "public");
        post5.setMedia(Collections.singletonList(
            new Media("https://pollinations.ai/p/futuristic%20green%20building%20with%20plants%20biophilic%20design", "image", "ai", 0)
        ));
        posts.add(post5);

        return posts;
    }
}
